### ISSUE TITLE
[Feature] EMR Studio with EMR on EKS using managed endpoint

### ISSUE THREAD

**Issue by victorgu-github** [awslabs/data-on-eks#86]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by lmouhib** [comment]
This is available in the cdk construct for the analytics reference
construct

**Comment by season1946** [comment]
@lmouhib EMR Studio? which part is for that? thx

**Comment by season1946** [comment]
As pointed by @lmouhib, the CDK solution can be found at  https://awslabs.github.io/data-on-eks/blog/Data%20Platform%20with%20AWS%20CDK
@vara-bonthu do we need a terraform solution? if not, we can close this issue.

**Comment by vara-bonthu** [comment]
It would be nice to show EMR Studio with one of the pattern using Terraform.

**Comment by vara-bonthu** [comment]
We might not need another blueprint for this. We can add this to **Workshop** content with a sub module to create EMR Studio and sample tests

**Comment by youngjeong46** [comment]
I want to revisit this issue if possible- I have a customer interested in leveraging EMR on EKS with Karpenter but have issues with actually provisioning the endpoint due to the Security Group of Karpenter not attaching to the endpoint ALB.

My thought was to use the existing blueprint with an example script that runs to manually attach the SG to the ALB so that the endpoint provisions successfully. But long term, it would be great to explore the possibility of automating (possibly collaborating with the Karpenter team)

**Comment by vara-bonthu** [comment]
@youngjeong46 Has this been resolved? Can we close this issue?

**Comment by youngjeong46** [comment]
Will close issue, resolved with PR #261
